language: node_js
node_js:
- '6'
deploy:
  provider: heroku
  api_key:
    secure: k6kS8+1yoeiIGVSdf7K/lJ03oseNJ4qY2EXSwB9z2ULbjH+Xiu0F7Xx8Dt8GiULxSgtWdTA/iEcPDomjEqeaz3VSdJbcTTt+E+vsyaNZhlQBdJAHC02QID8Hvl3oZ1mgwjO9eeBsH1P/8k/IPUaJidQTL/THz9tlBGQ3LIUhMffUDsVuPe3Srq314K5GIOOos4BMZ7WoSJ8ZApyISXlmD8nc9NJhAyTuTspeAm+nFpcZ8QdTKotcL5i6GzwoUNja1JJ6jW0LwqZbq2qUReZqO8FGdaB0macLom516DFKvZZKZh9hrKNU7T9g93mT74SUOzUXUV/QQlWkU8EznR5p2ZW62ZBFFWdxk33GibgrrDEtOvDJzZNARHj67Qn/pUfIjmWRFiZpuZiiLU/huLZMtppbGPG1uNphtOePqT+dwYPyE5cArnuf1PrxiFh5PEnbUtYDiaofLrxuFFIqqU5ZMrALW+as3QmTAfMZq2CrmRvskIVqKbxwa8D5BGkyKHaR1EueItrWJvuMx39DJ9Mag0/sHd6NYQElqqEyUjSvku4Rm5CLpasPs+glPj22Fki81ky80dawnB/xZCddN8SBNlOumtyDCwBdIbUW/LO9WRgTkoQ9qbyMvJMMxitY8Sar9XyKL66xPeJZXtE1jLdHtZTJ8JWOg2X4EF01tAHYx+0=
  app: ryanmunger
  on:
    repo: ryanmunger/ryanmunger
